# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea1a42979fd3ead294becf964fec30efff681a7897bcab3a6105684a47ce37e2a6070ebbbe944ae079241e3e99256d831ea92ebdde1742bbbb1e41658c80073d

test:
  secret_key_base: 043e9bbfd5043e75418f8e1d90e50defc2de5c4324e1d59c7ede71dab814030b394bd22375247c20861ba9c678677c043f1b1294f23df88c81750c6879f05a29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
